### ISSUE TITLE
Mau Nanya

### ISSUE THREAD

**Issue by nekokun11** [ekasyahwan/Sendinbox-#14]
Om skrng sendinbox masih di versi brp ? ( Yg paling baru )

**Comment by nekokun11** [comment]
Oh iya dan apa bedanya versi pro sama yg biasa ?

**Comment by ekasyahwan** [comment]
:v wkwkwkw , untuk versi bs cek di https://github.com/ekasyahwan/Sendinbox-

**Comment by nekokun11** [comment]
oc om ty :*
