### ISSUE TITLE
Masalah saat coba sent ke yahoo mail

### ISSUE THREAD

**Issue by Agusti7a** [ekasyahwan/Sendinbox-#17]
Ketika saya mencoba sent ke email yahoo, sendinbox nyan tidak muncul status sent nya. Padahal kalo di hotmail bisa bg. Kenapa itu?

**Comment by ekasyahwan** [comment]
bisa lampirkan screen shot ?

**Comment by Agusti7a** [comment]
ini adalah list yang saya coba, berada di directory /list/test.txt. http://prntscr.com/i1onmq
dan ini adalah hasil dari sendinbox nya. http://prntscr.com/i1ooxl

**Comment by ekasyahwan** [comment]
kok aneh mas :3

**Comment by Agusti7a** [comment]
gak tau bg

**Comment by Agusti7a** [comment]
sekali-kali ada muncul notif ini bg http://prntscr.com/i1ovhb,
ke aol juga gitu.

**Comment by rahmann0ob** [comment]
mau coba bantu jawab . 
coba buka smtp-config.
dibagian anti bounce nya ganti false

'anti_bounce' 			=> false,
